spring.application.name=K_Market
server.servlet.context-path=/K_Market


mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=org.example.k_market.entity
mybatis.configuration.map-underscore-to-camel-case=true
