spring.jpa.hibernate.ddl-auto=none

logging.level.org.springframework.web=INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=INFO
logging.level.org.mybatis=INFO
logging.level.org.apache.ibatis=INFO
logging.level.org.example.k_market.mapper=INFO

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB

server.forward-headers-strategy=framework
